name: build-ffmpeg
on:
  push:
    branches: main
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.txt'
  pull_request:
    branches: main
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.txt'
  workflow_dispatch:
jobs:
  build-qemu-stage-2:
#    needs: build-qemu-stage-1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64]
        os: [ubuntu-latest]
    env:
      stage: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: actions/download-artifact@v4
        with:
          name: stage-1-${{ matrix.os }}-${{ matrix.arch }}
          path: vendor
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: 12020330142
      - name: Build FFmpeg
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BEFORE_ALL_LINUX: cp -ar vendor /tmp
          CIBW_BEFORE_BUILD: python scripts/build-ffmpeg.py /tmp/vendor --stage ${{ env.stage }}
          CIBW_BUILD: cp39-*
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: LD_LIBRARY_PATH=/tmp/vendor/lib:$LD_LIBRARY_PATH auditwheel repair -w {dest_dir} {wheel}
          CIBW_SKIP: "*musllinux*"
          CIBW_TEST_COMMAND: python -c "import dummy"
        run: |
          pip install cibuildwheel
          cibuildwheel --output-dir output
          rm -f output/*.whl
        shell: bash
      - name: Upload FFmpeg
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.os }}-${{ matrix.arch }}
          path: output/
